"""empty message

Revision ID: 17704a0533c0
Revises: 26b1e2bea7a0
Create Date: 2023-05-26 23:50:43.017699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17704a0533c0'
down_revision = '26b1e2bea7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('blog', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
